spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: mileto
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect